/*
 * Copyright (C) 2015 Zhang Rui <bbcallen@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * https://github.com/Bilibili/jni4android
 * This file is automatically generated by jni4android, do not modify.
 */

#include "Process.h"


typedef struct J4AC_android_os_Process {
    jclass id;

    jmethodID method_setThreadPriority;
} J4AC_android_os_Process;
static J4AC_android_os_Process class_J4AC_android_os_Process;

void J4AC_android_os_Process__setThreadPriority(JNIEnv *env, jint priority)
{
    (*env)->CallStaticVoidMethod(env, class_J4AC_android_os_Process.id, class_J4AC_android_os_Process.method_setThreadPriority, priority);
}

void J4AC_android_os_Process__setThreadPriority__catchAll(JNIEnv *env, jint priority)
{
    J4AC_android_os_Process__setThreadPriority(env, priority);
    J4A_ExceptionCheck__catchAll(env);
}

int J4A_loadClass__J4AC_android_os_Process(JNIEnv *env)
{
    int         ret                   = -1;
    const char *J4A_UNUSED(name)      = NULL;
    const char *J4A_UNUSED(sign)      = NULL;
    jclass      J4A_UNUSED(class_id)  = NULL;
    int         J4A_UNUSED(api_level) = 0;

    if (class_J4AC_android_os_Process.id != NULL)
        return 0;

    sign = "android/os/Process";
    class_J4AC_android_os_Process.id = J4A_FindClass__asGlobalRef__catchAll(env, sign);
    if (class_J4AC_android_os_Process.id == NULL)
        goto fail;

    //public static final native void setThreadPriority(int priority)
    class_id = class_J4AC_android_os_Process.id;
    name     = "setThreadPriority";
    sign     = "(I)V";
    class_J4AC_android_os_Process.method_setThreadPriority = J4A_GetStaticMethodID__catchAll(env, class_id, name, sign);
    if (class_J4AC_android_os_Process.method_setThreadPriority == NULL)
        goto fail;

    J4A_ALOGD("J4ALoader: OK: '%s' loaded\n", "android.os.Process");
    ret = 0;
fail:
    return ret;
}
